### PR TITLE
Converted Pa to hPa

### PR DESCRIPTION
**Pull request by raspberrycoulis**
Your guide (https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-phat) refers to pressure in hPa, but the sensor reports in Pa. Have divided the pressure data by 100 to convert to hPa, which also falls in line with the BME680 breakout board readings.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you,

I think this change would break altitude calculation, see the additional other change in this similar PR here: https://github.com/pimoroni/enviro-phat/pull/24

If you could correct the other instance, I'd be happy to merge!

**Comment by raspberrycoulis** [comment]
Ok, I think I have done it as requested. Hope this helps @Gadgetoid

**Comment by Gadgetoid** [comment]
Oooo! I see what you did there :D Thank you.

**Comment by BillyDonahue** [comment]
I just got an enviro-phat and have no real stake here, but...

I realized that the values were in pascals before reading the docs and used them as pascals.
If I `pip update` my envirophat library, I'd like to know that my app won't break. Quietly changing the units returned by `pressure()` is a silently breaking API change. It's not so bad to continue returning pascals. It's easier and less surprising to just keep everything working the same and update the readme.

Maybe add new accessors or accessor arguments for different units, but leave the default `pressure()` accessor in pascals?

**Comment by Gadgetoid** [comment]
@BillyDonahue makes a good point, and this is the reason why I didn't rush this change out in the first place (when @sandyjmacdonald brought it up to me), despite acknowledging that hPa is the accepted standard.

While it's not uncommon to release a new library version X.0.0 with breaking changes, I'd rather not go throwing spanners into people's code. Perhaps we should add a `unit` to the `pressure()` method, something like so:

```python
    def pressure(self, unit=None):
        """Return the current air pressure.

        :param unit: String denoting unit scale to return; valid values: 'Pa' and 'hPa'

        """
        if unit is None:
            unit = 'Pa'

        self.update()
        if unit.lower() == 'hpa':
            return self._pressure / 100.0
        else:
            return self._pressure
```

**Comment by Gadgetoid** [comment]
See: https://github.com/pimoroni/enviro-phat/commit/a0e985617af39a67bfd9050e0c473785857fb156

This includes an update to `all.py` to demonstrate the use of hPa versus Pa.

**Pull request closed without merging**
