### PR TITLE
Formatting and function naming tweaks

### PR DESCRIPTION
**Pull request by raspberrycoulis**
Needed to update code to use `turn_on` instead of `lights_on` and also needed to fix an indentation issue relating to line 57 (`time.sleep(1)`).

### CODE REVIEW

**Comment by Gadgetoid** [comment]
This wont work, since the `lights_on` variable is the one checked in the `if` control flow, and `turn_on` is also a function name, so `turn_on = True` will replace `def turn_on()` and cause a `TypeError: 'bool' object is not callable` the next time that method is called.

https://github.com/raspberrycoulis/enviro-phat/blob/ae0ed8f373f19db55be222b1f23e462ff7b43fd0/examples/advanced/pi-lluminate.py#L78-L83

`lights_on` is fine, it just needs declared with a default value alongside state, low, high and period.

**Comment by raspberrycoulis** [comment]
Ok, thanks. I haven't got mine with me to test.

You mean something like this:
```
try:
    # Local variables.
    low = 260	# Low value for light level (lux).
    high = 300	# High value for light level (lux).
    period = 90	# Delay, in seconds, between calls.
    lights_on = False # Set the state of the lights to off.
    while True:
	# Get the average lux level first,
	room_light = average_lux()
	# Now check if the room is dark enough then turn on the lights.
	if room_light < low and not lights_on:
	    turn_on()
	    lights_on = True
	elif room_light > high and lights_on:
	    turn_off()
	    lights_on = False
	print("Waiting {} seconds before trying again".format(period))
	time.sleep(period)
except KeyboardInterrupt:
    pass
```

**Review by raspberrycoulis — COMMENTED** [review]
Defined `lights_on` in the local variables section to prevent the "TypeError: 'bool' object is not callable"

**Comment by raspberrycoulis** [comment]
@Gadgetoid, I’ve just tested this at home with my setup and it works fine now. Hope that helps.

**Comment by Gadgetoid** [comment]
Brilliant, thank you!

**Pull request merged**
